
[[_modules]]
= Modules
:subproject-base: {rootdir}/subprojects/griffon-miglayout-
:java-source: /src/main/java/
:groovy-source: /src/main/groovy/
:package-base: org/codehaus/griffon/runtime/
:numbered:

The following sections display all bindings per module. Use this information to
successfully override a binding on your own modules or to troubleshoot a module
binding if the wrong type has been applied by the Griffon runtime.

== JavaFX

Module name: `miglayout-javafx-groovy`

Depends on: `javafx-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}javafx-groovy{groovy-source}{package-base}javafx/miglayout/MiglayoutJavaFXGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node          | Type
| migLayoutPane | `{api_link_miglayoutpane}`
|===

== Swing

Module name: `miglayout-swing-groovy`

Depends on: `swing-groovy`

[source,java,options="nowrap"]
----
include::{subproject-base}swing-groovy{java-source}{package-base}swing/miglayout/MiglayoutSwingGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node      | Type
| migLayout | `net.miginfocom.swing.MigLayout`
|===

Both `migLayout` and `migLayoutPane` Nodes support the following properties

layoutConstraints:: Defines general constraints.
columnConstraints::  Defines constraints applicable to columns only.
rowConstraints:: Defines constraints applicable to rows only.

